
# # version
# apiVersion: apps/v1

# # this is 
# kind: Deployment
# metadata:
#   -name: name-deployment
# sepc:
#   replicas: 1
#   selector:
#     matchlabels:
#       app: second-app
#       tier: backendS
#   template:
#     metadata:
#       labels:
#         app: second-app
#         tier: backendS
#     spec:
#       containers:
#         - name: second-app
#           image: 
  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
      - name: second-app
        image: vinaycharlie/kub-first-app
